{% set name = "zarr-tools" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zarr-tools-{{ version }}.tar.gz
  sha256: fb445815036f4992074492019f728949286995b6cb4a52906989aa70f23e1329

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - dask-core
    - fire
    - nd2
    - python >=3.8
    - zarr

test:
  imports:
    - zarr_tools
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BaroudLab/zarr-tools
  summary: Convert nd2 to zarr
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
