{% set name = "zarr-tools" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 542367ffa8b4e18faf888d0463f4627d1f4117736c1e01eeb8324be8ae7f0104

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - dask-core
    - fire
    - nd2
    - python >=3.8
    - zarr

test:
  imports:
    - zarr_tools
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BaroudLab/zarr-tools
  summary: Convert nd2 to zarr
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
